-- ============================================
-- Academy database - Supabase
-- ============================================
-- Before/after running this SQL:
-- 1) Create admin@academy.local / 123456 in Authentication > Users.
-- 2) After creating the admin user, run the admin_profiles INSERT below.
-- 3) Deploy the included Edge Function: admin-athlete.

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  "brandName" text default 'استاد فرید آقادادی',
  "brandSubtitle" text default 'ارشد فیزیولوژی ورزشی | آکادمی تخصصی تناسب اندام',
  "logoUrl" text default 'academy-logo.svg',
  "heroBadge" text default 'آکادمی حرفه‌ای تناسب اندام و فیزیولوژی ورزشی',
  "heroTitle" text default 'مسیر قهرمانی و تحول فیزیک با استاد فرید آقادادی',
  "heroText" text default '',
  "heroImageUrl" text default '',
  phone text default '',
  address text default 'تهران، مجموعه تخصصی بدنسازی آکادمی فرید',
  instagram text default '',
  telegram text default '',
  whatsapp text default '',
  "footerText" text default '',
  "copyrightText" text default 'تمامی حقوق محفوظ است © ۲۰۲۶ | آکادمی تخصصی تناسب اندام استاد فرید آقادادی'
);
insert into public.site_settings(id) values(1) on conflict(id) do nothing;
update public.site_settings set "logoUrl"='academy-logo.svg' where id=1 and coalesce("logoUrl",'')='';

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_academy_admin()
returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.admin_profiles where user_id=auth.uid()); $$;

-- After creating admin@academy.local:
-- insert into public.admin_profiles(user_id)
-- select id from auth.users where email='admin@academy.local'
-- on conflict(user_id) do nothing;

alter table public.site_settings enable row level security;
drop policy if exists "site settings public read" on public.site_settings;
create policy "site settings public read" on public.site_settings for select to anon,authenticated using(true);
drop policy if exists "site settings admin insert" on public.site_settings;
create policy "site settings admin insert" on public.site_settings for insert to authenticated with check(public.is_academy_admin());
drop policy if exists "site settings admin update" on public.site_settings;
create policy "site settings admin update" on public.site_settings for update to authenticated using(public.is_academy_admin()) with check(public.is_academy_admin());

-- Students: one row per athlete, linked to a real Supabase Auth user.
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  phone text not null unique,
  goal text default 'تناسب اندام',
  status text not null default 'فعال',
  tuition_amount numeric(12,0) not null default 0,
  paid_amount numeric(12,0) not null default 0,
  last_payment_date date,
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;
drop policy if exists "students admin all" on public.students;
create policy "students admin all" on public.students for all to authenticated using(public.is_academy_admin()) with check(public.is_academy_admin());
drop policy if exists "students athlete own read" on public.students;
create policy "students athlete own read" on public.students for select to authenticated using(auth.uid()=user_id);

-- Payment history.
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  amount numeric(12,0) not null check(amount>=0),
  payment_date date not null default current_date,
  note text default '',
  recorded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.payments enable row level security;
drop policy if exists "payments admin all" on public.payments;
create policy "payments admin all" on public.payments for all to authenticated using(public.is_academy_admin()) with check(public.is_academy_admin());
drop policy if exists "payments athlete own read" on public.payments;
create policy "payments athlete own read" on public.payments for select to authenticated using(exists(select 1 from public.students s where s.id=student_id and s.user_id=auth.uid()));

-- Messages.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  sender text not null,
  phone text not null,
  text text not null,
  reply text default '',
  created_at timestamptz not null default now(),
  replied_at timestamptz
);
alter table public.messages add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.messages enable row level security;
drop policy if exists "messages authenticated insert own" on public.messages;
create policy "messages authenticated insert own" on public.messages for insert to authenticated with check(auth.uid()=user_id and char_length(text) between 1 and 4000);
drop policy if exists "messages user read own" on public.messages;
create policy "messages user read own" on public.messages for select to authenticated using(auth.uid()=user_id or public.is_academy_admin());
drop policy if exists "messages admin update" on public.messages;
create policy "messages admin update" on public.messages for update to authenticated using(public.is_academy_admin()) with check(public.is_academy_admin());
drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete" on public.messages for delete to authenticated using(public.is_academy_admin());

-- Storage for banner/other public site media. Logo is a fixed SVG in the website and is NOT uploaded by the admin.
insert into storage.buckets(id,name,public) values('academy-images','academy-images',true) on conflict(id) do update set public=true;
drop policy if exists "academy images public read" on storage.objects;
create policy "academy images public read" on storage.objects for select to public using(bucket_id='academy-images');
drop policy if exists "academy images admin upload" on storage.objects;
create policy "academy images admin upload" on storage.objects for insert to authenticated with check(bucket_id='academy-images' and public.is_academy_admin());
drop policy if exists "academy images admin update" on storage.objects;
create policy "academy images admin update" on storage.objects for update to authenticated using(bucket_id='academy-images' and public.is_academy_admin()) with check(bucket_id='academy-images' and public.is_academy_admin());
drop policy if exists "academy images admin delete" on storage.objects;
create policy "academy images admin delete" on storage.objects for delete to authenticated using(bucket_id='academy-images' and public.is_academy_admin());
