-- Academy Supabase setup
-- Run this in Supabase SQL Editor.

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  "brandName" text default 'استاد فرید آقادادی',
  "brandSubtitle" text default 'ارشد فیزیولوژی ورزشی | آکادمی تخصصی تناسب اندام',
  "logoUrl" text default '',
  "heroBadge" text default 'آکادمی حرفه‌ای تناسب اندام و فیزیولوژی ورزشی',
  "heroTitle" text default 'مسیر قهرمانی و تحول فیزیک با استاد فرید آقادادی',
  "heroText" text default '',
  "heroImageUrl" text default '',
  phone text default '',
  address text default '',
  instagram text default '',
  telegram text default '',
  whatsapp text default '',
  "footerText" text default '',
  "copyrightText" text default ''
);

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

alter table public.site_settings enable row level security;

-- Public visitors can read the site settings.
drop policy if exists "site settings public read" on public.site_settings;
create policy "site settings public read" on public.site_settings for select to anon, authenticated using (true);

-- Logged-in Supabase users can update settings.
drop policy if exists "site settings authenticated update" on public.site_settings;
create policy "site settings authenticated update" on public.site_settings for update to authenticated using (true) with check (true);

-- Messages table for the public contact inbox.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  phone text not null,
  text text not null,
  reply text default '',
  created_at timestamptz not null default now(),
  replied_at timestamptz
);

alter table public.messages enable row level security;

-- Public users can send messages.
drop policy if exists "messages public insert" on public.messages;
create policy "messages public insert" on public.messages for insert to anon, authenticated with check (char_length(text) between 1 and 4000);

-- Public read is intentionally disabled. Admin message management should be done after authentication.
-- For a production build, create an admin-only policy using your Supabase Auth user id.
