-- ============================================
-- Academy / Supabase complete schema
-- Run this entire file in Supabase SQL Editor
-- ============================================

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  "brandName" text default 'استاد فرید آقادادی',
  "brandSubtitle" text default 'ارشد فیزیولوژی ورزشی | آکادمی تخصصی تناسب اندام',
  "logoUrl" text default '',
  "heroBadge" text default 'آکادمی حرفه‌ای تناسب اندام و فیزیولوژی ورزشی',
  "heroTitle" text default 'مسیر قهرمانی و تحول فیزیک با استاد فرید آقادادی',
  "heroText" text default '',
  "heroImageUrl" text default '',
  phone text default '',
  address text default '',
  instagram text default '',
  telegram text default '',
  whatsapp text default '',
  "footerText" text default '',
  "copyrightText" text default ''
);

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_academy_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = auth.uid()
  );
$$;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  sender text not null,
  phone text not null,
  text text not null check (char_length(text) between 1 and 4000),
  reply text default '',
  created_at timestamptz not null default now(),
  replied_at timestamptz
);

alter table public.site_settings enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.messages enable row level security;

drop policy if exists "site settings public read" on public.site_settings;
create policy "site settings public read"
on public.site_settings for select
to anon, authenticated using (true);

drop policy if exists "site settings admin insert" on public.site_settings;
create policy "site settings admin insert"
on public.site_settings for insert
to authenticated
with check (public.is_academy_admin());

drop policy if exists "site settings admin update" on public.site_settings;
create policy "site settings admin update"
on public.site_settings for update
to authenticated
using (public.is_academy_admin())
with check (public.is_academy_admin());

drop policy if exists "messages authenticated insert own" on public.messages;
create policy "messages authenticated insert own"
on public.messages for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "messages user read own" on public.messages;
create policy "messages user read own"
on public.messages for select
to authenticated
using (auth.uid() = user_id or public.is_academy_admin());

drop policy if exists "messages admin update" on public.messages;
create policy "messages admin update"
on public.messages for update
to authenticated
using (public.is_academy_admin())
with check (public.is_academy_admin());

drop policy if exists "messages admin delete" on public.messages;
create policy "messages admin delete"
on public.messages for delete
to authenticated
using (public.is_academy_admin());

-- ============================================
-- Storage برای لوگو و بنر
-- ============================================

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update set public = true;

drop policy if exists "site media public read" on storage.objects;
create policy "site media public read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'site-media');

drop policy if exists "site media admin upload" on storage.objects;
create policy "site media admin upload"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'site-media'
  and public.is_academy_admin()
);

drop policy if exists "site media admin update" on storage.objects;
create policy "site media admin update"
on storage.objects for update
to authenticated
using (
  bucket_id = 'site-media'
  and public.is_academy_admin()
)
with check (
  bucket_id = 'site-media'
  and public.is_academy_admin()
);

drop policy if exists "site media admin delete" on storage.objects;
create policy "site media admin delete"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'site-media'
  and public.is_academy_admin()
);

-- ============================================
-- بعد از ساخت کاربر admin در Authentication:
-- این دستور را با همان ایمیل اجرا کن.
-- ============================================
-- insert into public.admin_profiles (user_id)
-- select id from auth.users
-- where email = 'admin@academy.local'
-- on conflict (user_id) do nothing;
